import "sanitize.css";
import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Calculator Constructor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
